//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTPIZZA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.TuyenDungs = new HashSet<TuyenDung>();
        }
    
        public int MaAdmin { get; set; }
        public string HovaTen { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> IdPhanQuyen { get; set; }
        public Nullable<int> IdChiNhanh { get; set; }
    
        public virtual PhanQuyen PhanQuyen { get; set; }
        public virtual Login Login { get; set; }
        public virtual ChiNhanh ChiNhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuyenDung> TuyenDungs { get; set; }
    }
}
