//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTPIZZA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HOTPIZZAEntities1 : DbContext
    {
        public HOTPIZZAEntities1()
            : base("name=HOTPIZZAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<ChiNhanh> ChiNhanhs { get; set; }
        public virtual DbSet<CTDonDatHang> CTDonDatHangs { get; set; }
        public virtual DbSet<DanhMucMon> DanhMucMons { get; set; }
        public virtual DbSet<DonDatHang> DonDatHangs { get; set; }
        public virtual DbSet<Giohang> Giohangs { get; set; }
        public virtual DbSet<GopYKhachHang> GopYKhachHangs { get; set; }
        public virtual DbSet<HinhThucThanhToan> HinhThucThanhToans { get; set; }
        public virtual DbSet<KhaiVivaSalad> KhaiVivaSalads { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<MonAnKem> MonAnKems { get; set; }
        public virtual DbSet<MonChinhvaMiY> MonChinhvaMiYs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<Pizza> Pizzas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThucUong> ThucUongs { get; set; }
        public virtual DbSet<TinhTrangDonHang> TinhTrangDonHangs { get; set; }
        public virtual DbSet<TrangMieng> TrangMiengs { get; set; }
        public virtual DbSet<TuyenDung> TuyenDungs { get; set; }
    }
}
