//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTPIZZA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAnKem
    {
        public string IdMonAnKem { get; set; }
        public string TenMonAnKem { get; set; }
        public string IdDanhMuc { get; set; }
        public string HinhMinhHoa { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual DanhMucMon DanhMucMon { get; set; }
    }
}
